config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"

  get "home" => "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"

  resources :users do
    resources :skill_users
    get "add_skills" => "skill_users#show"
  end

  namespace :admin do
    root "users#index"
    resources :skills, :users, :teams, :positions,
              :projects
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  include ActivityLogs
  extend CsvExport

  has_many :skill_users, dependent: :destroy
  has_many :users, through: :skill_users

  validates :name, presence: true

  after_create :log_create
  after_update :log_update
  after_destroy :log_destroy

  private
  def log_create
    create_activity_log Settings.activities.create, self.class.name
  end

  def log_update
    create_activity_log Settings.activities.update, self.class.name
  end

  def log_destroy
    create_activity_log Settings.activities.destroy, self.class.name
  end
end

app/controllers/admin/skills_controller.rb
class Admin::SkillsController < ApplicationController
  before_action :admin_user

  def index
    @skills = Skill.paginate page: params[:page],
                             per_page: Settings.number_per_page
    respond_to do |format|
      format.html
      format.csv {send_data @skills.to_csv}
    end
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new skill_params
    if @skill.save
      flash[:success] = t "skill.created"
      redirect_to admin_skills_path
    else
      render :new
    end
  end

  def edit
    @skill = Skill.find params[:id]
  end

  def update
    @skill = Skill.find params[:id]
    if @skill.update_attributes skill_params
      flash[:success] = t "skill.updated"
      redirect_to admin_skills_path
    else
      render :edit
    end
  end

  def destroy
    Skill.find(params[:id]).destroy
    flash[:success] = t "skill.deleted"
    redirect_to admin_skills_path
  end

  private
  def skill_params
    params.require(:skill).permit :name
  end
end

app/views/admin/skills/_form.html.erb
<%= form_for [:admin, @skill] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="fields">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit t("submit"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/skills/_skill.html.erb
<tr>
  <td><%= link_to skill.name, admin_skill_path(skill) %></td>
  <td><%= skill.created_at %></td>
  <td><%= link_to "", edit_admin_skill_path(skill),
              class: "glyphicon glyphicon-edit" %>
      <%= link_to "", admin_skill_path(skill), method: :delete,
              data: {confirm: t("yas")},
              class: "glyphicon glyphicon-trash" %>
  </td>
</tr>

app/views/admin/skills/edit.html.erb
<h1><%= t "skill.edit" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <br><%= link_to t("back"), admin_skills_path %>
  </div>
</div>

app/views/admin/skills/index.html.erb
<h1><%= t "skill.list" %></h1>

<%= link_to t("skill.new"), new_admin_skill_path,
                            class: "glyphicon glyphicon-plus" %>
<%= will_paginate %>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th><%= t :name %></th>
        <th><%= t :time %></th>
        <th><%= t :tool %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @skills %>
    </tbody>
  </table>
</div>
<%= will_paginate %>
<%= link_to t("csv.export"), admin_skills_path(format: "csv"), class: "btn btn-success" %>

app/views/admin/skills/new.html.erb
<h1><%= t "skill.new" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <br><%= link_to t(:back), admin_skills_path %>
  </div>
</div>