config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"

  get "home" => "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"

  resources :users do
    resources :skill_users
    get "add_skills" => "skill_users#show"
  end

  namespace :admin do
    root "users#index"
    resources :skills, :users, :teams, :positions,
              :projects
  end
end

app/models/position.rb
class Position < ActiveRecord::Base
  include ActivityLogs
  extend CsvExport

  belongs_to :user

  after_create :log_create
  after_update :log_update
  after_destroy :log_destroy

  private
  def log_create
    create_activity_log Settings.activities.create, self.class.name
  end

  def log_update
    create_activity_log Settings.activities.update, self.class.name
  end

  def log_destroy
    create_activity_log Settings.activities.destroy, self.class.name
  end
end

app/controllers/admin/positions_controller.rb
class Admin::PositionsController < ApplicationController
  before_action :admin_user

  def index
    @positions = Position.paginate page: params[:page],
                                   per_page: Settings.number_per_page
    respond_to do |format|
      format.html
      format.csv {send_data @positions.to_csv}
    end
  end

  def new
    @position = Position.new
  end

  def create
    @position = Position.new position_params
    if @position.save
      flash[:success] = t "position.created"
      redirect_to admin_positions_path
    else
      render :new
    end
  end

  def destroy
    Position.find(params[:id]).destroy
    flash[:success] = t "position.deleted"
    redirect_to admin_positions_path
  end

  private
  def position_params
    params.require(:position).permit :name, :abbreviation
  end
end

app/views/admin/positions/_form.html.erb
<%= form_for [:admin, @position] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="fields">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :abbreviation %>
     <%= f.text_field :abbreviation, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit t("position.create"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/positions/_position.html.erb
<tr>
  <td><%= position.id %></td>
  <td><%= position.name %></td>
  <td><%= position.abbreviation %></td>
  <td>
    <%= link_to "", edit_admin_position_path(position), class: "glyphicon glyphicon-edit" %>
    <%= link_to "", admin_position_path(position.id), method: :delete, data: {confirm: t("yas")}, 
                    class: "glyphicon glyphicon-trash" %>
  </td>
</tr>

app/views/admin/positions/index.html.erb
<h1><%= t "position.list" %></h1>

<button>
  <%= link_to t("position.new"), new_admin_position_path, class: "glyphicon glyphicon-plus" %>
</button>
<%= will_paginate %>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th><%= t "position.id" %></th>
        <th><%= t "position.name" %></th>
        <th><%= t "position.abbreviation" %></th>
        <th><%= t "action" %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @positions %>
    </tbody>
  </table>
</div>
<%= will_paginate %>
<%= link_to t("csv.export"),  admin_positions_path(format: "csv"), class: "btn btn-success" %>

app/views/admin/positions/new.html.erb
<h1><%= t "position.new" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <br><%= link_to t(:back), admin_positions_path %>
  </div>
</div>