config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"

  get "home" => "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"

  resources :users do
    resources :skill_users
    get "add_skills" => "skill_users#show"
  end

  namespace :admin do
    root "users#index"
    resources :skills, :users, :teams, :positions,
              :projects
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include ActivityLogs
  extend CsvExport

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :skill_users, dependent: :destroy
  has_many :skills, through: :skill_users

  has_many :team_users
  has_many :teams, through: :team_users

  has_many :project_users
  has_many :projects, through: :project_users

  has_one :leader, class_name: "Team", foreign_key: "leader_id"
  has_one :leader_project, class_name: "Project", foreign_key: "leader_id"

  accepts_nested_attributes_for :skill_users, allow_destroy: true

  scope :users_not_in_team, ->{where Settings.sql.user.team_users_scope}
  scope :normal_users, ->{where Settings.sql.user.normal_users}

  after_create :log_create
  after_update :log_update
  after_destroy :log_destroy

  private
  def log_create
    create_activity_log Settings.activities.create, self.class.name
  end

  def log_update
    create_activity_log Settings.activities.update, self.class.name
  end

  def log_destroy
    create_activity_log Settings.activities.destroy, self.class.name
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user

  def index
    @users = User.paginate page: params[:page],
                           per_page: Settings.number_per_page
    @users = @users.normal_users
    respond_to do |format|
      format.html
      format.csv {send_data @users.to_user_csv}
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "user.created"
      redirect_to admin_root_path
    else
      flash[:danger] = t "user.create_fail"
      render :new
    end
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    flash[:success] = t "user.deleted"
    redirect_to admin_root_path
  end

  private
  def user_params
    params.require(:user).permit :name, :birthday, :email, :password, :is_admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes user_params
      if params[:flag] == Settings.done
        redirect_to @user
      else
        redirect_to user_add_skills_path(current_user)
      end
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :birthday, :email, :encrypted_password,
      skill_users_attributes: [:id, :level, :used_years, :_destroy],
      skill_ids: []
  end
end

app/views/admin/users/_user.html.erb
<tr>
  <td><%= link_to user.name, admin_user_path(user) %></td>
  <td><%= user.email %></td>
  <td><%= t "team.team" %></td>
  <td>
    <%= link_to "", edit_admin_user_path(user), class: "glyphicon glyphicon-edit" %>
    <%= link_to "", admin_user_path(user.id), method: :delete, data: {confirm: t("ays")}, 
                    class: "glyphicon glyphicon-trash" %>
  </td>
</tr>

app/views/admin/users/index.html.erb
<h1><%= t "user.list" %></h1>

<button>
  <%= link_to t("user.new"), new_admin_user_path, class: "glyphicon glyphicon-plus" %>
</button>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th><%= t "user.name" %></th>
        <th><%= t "user.email" %></th>
        <th><%= t "team.team" %></th>
        <th><%= t "action" %></th>
      </tr>
    </thead>
    <tbody>
    <%= will_paginate @users%>
      <%= render partial: "user", collection: @users %>
    <%= will_paginate @users%>
    </tbody>
  </table>
</div>
<%= link_to t("csv.export"), admin_users_path(format: "csv"), class: "btn btn-success" %>

app/views/admin/users/new.html.erb
<h2><%= t "user.new" %></h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @user] do |f| %>
      <%= render "shared/error_messages", object: @user %>

      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :birthday %><br />
        <%= f.date_select :birthday, start_year: 1950  %>
      </div>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password, autocomplete: "off" %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off" %>
      </div>

      <div class="field">
        <%= f.check_box :is_admin %>
        <%= f.label t("user.is_admin") %>
      </div>

      <div class="actions">
        <%= f.submit t("user.create") %>
      </div>
    <% end %>
  </div>
</div>