config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"

  get "home" => "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"

  resources :users do
    resources :skill_users
    get "add_skills" => "skill_users#show"
  end

  namespace :admin do
    root "users#index"
    resources :skills, :users, :teams, :positions,
              :projects
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to t("help"), help_path %></li>
      <li><%= link_to t("about"), about_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if user_signed_in? && current_user.is_admin? %>
      <%= link_to t("admin_title"), admin_root_path, id: "logo" %>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href= "#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t "position.position" %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t("position.list"), admin_positions_path %></li>
            <li><%= link_to t("position.create"), new_admin_position_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href= "#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t "skill.skill" %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t("skill.list"), admin_skills_path %></li>
            <li><%= link_to t("skill.create"), new_admin_skill_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href= "#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t "team.team" %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t("team.list"), admin_teams_path %></li>
            <li><%= link_to t("team.create"), new_admin_team_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href= "#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t "project.project" %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t("project.list"), admin_projects_path %></li>
            <li><%= link_to t("project.create"), new_admin_project_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href= "#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t "csv.csv" %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t("csv.import"), "#" %></li>
            <li><%= link_to t("csv.export"), "#" %></li>
          </ul>
        </li>
      </ul>
    <% else %>
      <%= link_to t("title"), root_path, id: "logo" %>
    <% end %>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href= "#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.email %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t("view_profile"), current_user %></li>
            <li>
              <%= link_to t("edit_profile"), edit_user_registration_path %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to t("logout"), destroy_user_session_path, method: "delete" %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to t(:login), new_user_session_path %></li>
        <li><%= link_to t(:signup), new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MMS_10</title>
  <%= stylesheet_link_tag    'application', media: 'all',
    'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application',
    'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header'%>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer'%>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>